### ISSUE TITLE
No dictionary imagery in Extension manager

### ISSUE THREAD

**Issue by tmtisfree** [Lootyhoof/aeromoon#1]
As I don't know how to use the pull request in this system, here is the picture I use and the modified CSS file in lines 275-277 chrome/mozapps/extensions/extensions.css (renamed as a .txt).

![category-dictionaries](https://cloud.githubusercontent.com/assets/10900483/20866370/69e6771e-ba2c-11e6-8545-a080511b6f7e.png)

[extensions.css.txt](https://github.com/Lootyhoof/aeromoon/files/629537/extensions.css.txt)

**Comment by Lootyhoof** [comment]
Thanks! While the icon you provided is good I ultimately opted for the icon used in the default theme, as it works quite nicely with the other icons in there. :)
