### ISSUE TITLE
No more separator in download list PM 27

### ISSUE THREAD

**Issue by tmtisfree** [Lootyhoof/aeromoon#2]
Apparently the 1px bottom border which separate items in the download list has been dropped in PM 27, resulting in a difficult to read list. You may wish to add it again for consistency with the aim of this theme. Go to:

src/chrome/browser/downloads/allDownloadsViewOverlay.css

and add at the end of the following rule:

#downloadsRichListBox > richlistitem.download {

this line:

  border-bottom: 1px solid ThreeDLightShadow;

The separator will then appear in the download tab, sidebar and window.

Thank you.

**Comment by Lootyhoof** [comment]
This styling was never present for that particular part of the theme (the places window), however it looks to be a nice improvement, so I'll use it. Thanks!

This has been added in https://github.com/Lootyhoof/aeromoon/commit/a80b0ecdf4cca54dd8bd75fe1a5b3bd2a0ef94a9.

**Comment by tmtisfree** [comment]
I think that you can add the CSS rule to all your other themes as well.
