### ISSUE TITLE
Minor inaccuracies 

### ISSUE THREAD

**Issue by ghost** [Lootyhoof/aeromoon#3]
- The left edge of the identity box is not rounded as Firefox 3.6, misses glow behind the favicon

- Tabs and new tab button lack animated highlight on hover

- List All Tabs button is opaque instead of translucent

- Location/search bar backgrounds should be always be #ffffff

**Comment by Lootyhoof** [comment]
Can you show me what you mean about the favicon glow? I can't see this on Firefox 3.6. The animated highlight is an odd one too - the PNG is the same and is being used, and correctly animates, but doesn't seem to show on tab hover. I'm not sure what can be done about this one, but we'll see.

The rest should be resolved.

**Comment by ghost** [comment]
@Lootyhoof ![capturar](https://user-images.githubusercontent.com/13562431/46907448-da991480-cee8-11e8-8d12-c0c61dca55dc.PNG)

**Comment by Lootyhoof** [comment]
There's no reliable way of getting that in unfortunately. In the Firefox 3.6 days the XUL structure was different such that that type of effect was possible, but not so much these days. It's something I'd considered when initially porting this theme, but ultimately had to not implement.
